#!/usr/bin/env bash

# Escapes multiline text for github actions expression
# Adapted from https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/td-p/37870

content=$(cat "${1:-/dev/stdin}")
content="${content//'%'/'%25'}"
content="${content//$'\n'/'%0A'}"
content="${content//$'\r'/'%0D'}"
echo "$content"
