on: [push]

jobs:
  latest_retro_text_job:
    runs-on: ubuntu-latest
    name: get latest retro text
    steps:
      - uses: actions/checkout@v2
      - name: Get text
        id: get_retro_text
        uses: tooky/retro-tools-latest-text-action@main
      - name: Print text
        run: echo "${{ steps.get_retro_text.outputs.text }}"
