on: [push]

jobs:
  latest_retro_text_job:
    runs_on: ubuntu-latest
    name: get latest retro text
    steps:
    - name: Get text
      id: get_retro_text
      uses: tooky/retro-tools-latest-text-action@v0.0.1
    - name: Get the text
      run: echo "${{ steps.get_retro_text.outputs.text }}"
